name: Check Branch and Author

on:
  push:
    branches:
      - main

jobs:
  check-branch-and-author:
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch and Author
      run: |
        if [ "${GITHUB_REF##*/}" != "main" ]; then
          echo "Push to branches other than main is not allowed."
          exit 1
        fi

        if [ "${GITHUB_ACTOR}" != "ThugPigeon653" ]; then
          echo "Push by authors other than ThugPigeon653 is not allowed."
          exit 1
        fi
