name: Check Branch and Author

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-and-author:
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch and Author
      run: |
        if [ "${GITHUB_REF}" = "refs/heads/main" ] && [ "${GITHUB_ACTOR}" != "ThugPigeon653" ]; then
          echo "Direct push to main is not allowed. Please use a pull request."
          exit 1
        fi